name: Release
# we run standard-version via lerna

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: mikeal/publish-to-github-action@master
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          yarn install
          yarn lerna publish
          git fetch origin -p develop:develop
          git push origin
          git checkout develop
          git push origin
