on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: ${{env.ACTION_NAME}}
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        if: ${{ steps.release.outputs.release_created }}
      # - run: npm ci
      - run: >
          yarn install --frozen-lockfile &&
          yarn test
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn lerna publish from-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
